language: c
dist: xenial
sudo: required
cache:
  directories:
    - /usr/local/lib
    - /usr/local/include
addons:
  apt:
    packages:
    - git
    - curl
    - wget
install:
- sudo bash scripts/provision.sh
script:
- exit 0
