language: c
dist: xenial
sudo: required
cache:
  directories:
    - deps/
addons:
  apt:
    packages:
    - git
    - wget
install:
- sudo scripts/provision.sh
script:
- make
- ls -al bin/
- ldd bin/*-static
